---
# tasks file for php

- name: Install php
  dnf:
    name:
      - php
      - php-mysqlnd
    update_cache: yes
    state: latest

- name: Restart Apache service
  service:
      name: httpd
      state: restarted
